language: java
sudo: false
script: mvn install
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Eaglestriker"
      - git config --local user.email "dubath.tim@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: vI0Xzm58sKwkQvmUmugxGjvHVRS3wDBnTdtOo9mTh3Zu7aaw+iLxRQCD18+DtJ8d5hmJ6HWAf4Ots3bz5SURGkHHCLnetONqXJRVWKXLmfMkjiB4SQr2zz0X5h7PN4KWuLOCiknIFTNP83X9nBlwD2pJ/XfaFIyjKPVr3mTpN8zmyxwKTC4VUnmnmRkwcS7WpkJuiFHCxft9qFT4QfvB4ndyxGCN8ktTrQJaU9LEh0GSLEe+pEfDDe7aUlYVxlIJb2GDYK6wM5r/rfKx07M27NlIBld5yEL7mYIUQEb5Q2yT1MUqGjXXXmCNqC4N/wQJHL16odPrfLGO1/MCCKIkj0rOlGvkrDtqgxdG9xMifYyhf+MSy3vsSsrxpyrTJst+ROZ90zb8g3g3EN0defPUcuGrGsRjhLftvJP7ZTyqQd5c+bhGWxFXKSpmsFlnaTNAtTscXGrACDYKotyT5ntoVrU1zTswgSDHmPEEscFFwX/hUPx/3rOOWN5G1eK0PRqZHLzUvUns/aJKMDZw+jFPN/dDVD2ho5jRgXXEsHZ2CS8fvtSMJx13ENCQ1O6RqOOROBWasetzj7n6O/WePCEclrvNI6RMcfFhWJH+56JEWJmoPWValU/37p+XCMphqPb/+dofzie7X1NAmaGN7j1jI54PesinNiYKK+AUFMTlHZQ=
  file: "/home/travis/.m2/repository/ch/bbw/td/03_CrepsWithMockito/0.0.1/03_CrepsWithMockito-0.0.1.jar"
  on:
    repo: Eaglestriker/03_01_CrapsWithMockitoMaven